
exports.seed = function(knex) {
  return knex('relevantPricing').insert([
    {
      productName:"Wheat Flour",
      image:"http://agrodaily.com/wp-content/uploads/2016/04/wheat.png",
      price:4,
      category_id:"3",
      sub_id:"11",
      location_id:15
    },
    {
      productName:"Beef",
      image:"https://purepng.com/public/uploads/large/purepng.com-meatfood-meat-red-fresh-grill-cook-beef-steak-9415246237676ksid.png",
      price:12,
      category_id:"1",
      sub_id:"3",
      location_id:15
    },
    {
      productName:"Milk",
      image:"https://images.vexels.com/media/users/3/160371/isolated/preview/6c40e6ebea6870c673bc72d8f215724d-milk-box-milk-cow-illustration-by-vexels.png",
      price:5,
      category_id:"1",
      sub_id:"2",
      location_id:15
    },
    {
      productName:"Sweet Potatoes",
      image:"https://i.imgur.com/LwiGxoD.jpg",
      price:8,
      category_id:"7",
      sub_id:"19",
      location_id:2
    },
    {
      productName:"Eggs",
      image:"http://www.pngplay.com/wp-content/uploads/2/Eggs-Transparent-Background.png",
      price:3,
      category_id:"1",
      sub_id:"2",
      location_id:2
    },
    {
      productName:"Honey",
      image:"http://www.pngplay.com/wp-content/uploads/1/Honey-PNG-Image.png",
      price:7,
      category_id:"1",
      sub_id:"2",
      location_id:6
    },
    {
      productName:"Millet Grain",
      image:"https://www.pngarts.com/files/5/Millet-PNG-Download-Image.png",
      price:15,
      category_id:"3",
      sub_id:"8",
      location_id:6
    },
    {
      productName:"Tomatoes",
      image:"https://i.imgur.com/l8Z2g9p.jpg",
      price:1,
      category_id:"9",
      sub_id:"32",
      location_id:9
    },
    {
      productName:"Cowpeas",
      image:"https://i.imgur.com/iLVkoAi.jpg",
      price:9,
      category_id:"9",
      sub_id:"9",
      location_id:9
    },
    {
      productName:"Tilapia",
      image:"https://www.supremelobster.com/wp-content/uploads/tilapia.png",
      price:18,
      category_id:"1",
      sub_id:"2",
      location_id:9
    },
    {
      productName:"Goat",
      image:"https://i.imgur.com/jApguL1.jpg",
      price:12,
      category_id:"1",
      sub_id:"3",
      location_id:15
    },
    {
      productName:"Raw Honey",
      image:"https://i.imgur.com/L65zYph.jpg",
      price:7,
      category_id:"1",
      sub_id:"2",
      location_id:6
    },
  ])
    
};
